services:
  model_builder:
    build:
      context: .
      dockerfile: Dockerfile
    image: model_builder
    ports:
      - "8888:8888"
    networks:
      - project_network
    privileged: true 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./../:/home/jovyan/work

  postgres:
    image: postgres:latest
    container_name: postgres_server
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    networks:
      - project_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sqlServer/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:


networks:
  project_network:
    driver: bridge
